AllCops:
  DisplayCopNames: true

# ---------------------- Metrics ----------------------

Metrics/BlockLength:
  Exclude:
    - tuga.gemspec

Metrics/LineLength:
  Max: 120

# ----------------------- Style -----------------------

Style/FrozenStringLiteralComment:
  Enabled: false
