require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  NewCops: enable

# ---------------------- Metrics ----------------------

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - tuga.gemspec

Metrics/LineLength:
  Max: 120

# ----------------------- RSpec -----------------------

RSpec/ExampleLength:
  Enabled: false

# ----------------------- Style -----------------------

Style/FrozenStringLiteralComment:
  Enabled: false
