require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - lib/tuga/ruby_parser_patches.rb

# ----------------------- Layout ----------------------

Layout:
  Max: 120

# ---------------------- Metrics ----------------------

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - tuga.gemspec

# ----------------------- RSpec -----------------------

RSpec/ExampleLength:
  Enabled: false

# ------------------- Security/Eval -------------------
Security/Eval:
  Exclude:
    - bin/tuga

# ----------------------- Style -----------------------

Style/FrozenStringLiteralComment:
  Enabled: false
